---
language: python
env:
  global:
  - secure: "ePn6eMl43FKtVkVRbSU7vcGnF4zQ4v4U6fyUbLec0FcE4gVLksd5G1MVzaW7lqkka8WpN5cB58bWLWKkIkDf/RP54saADMl3gyl9XtGEd7oKP5rgPY/dD77Z9e29pDpikbUU0y3nKyojTCpHAOrvs+XDB9PP2fmayt0XiU/5yFBTYY6tCcUkOUIWW+w4BZCzvcDszGow3gGyVvOqcbDHGDTMMNT4XwPA/AqDKWRoJ+f840axz/VglPPIFUJjz1DRw+mfYc9HYIfxH90vW6bilhS5ZyEfm31MH6WVpLF/FKvOx5L7aZw+iiIzR6zNviePtbIhAs2UgFZei85xOw/j8vwB6QkzJv3FRB8ZaYuFv/y7I5OPdORkBwHtpKtsw530hSKj6X7Rk753vDezCQU9e5IgW0McZuTh/P1owp3kUaHhEWEldxs8o5uNt9dZvgPbHCL63y6R5kddaIgdogWiBZcgAboo3Vtz5npoijA0UOQk+LHOJCqYjVPsbj09g4URzW3NBh0zEbgD10gZ+6oWx/UpbIIA+/mNe3LltqePEmHjhIjkNtvOBKXGlSrBNguX/5CylAVWY80MVxpCatsordTEHjCkKRM1Wj6vkqOjZmEDcp0LhMXMb/qPntzsVSY1M6lqsj3CAHX0QRRxTPRrEnbdEf2CQpKjS6RfsnDt4Zg="
  - secure: "ldwGMqG//c0As6jBkxVcUUJCBPuABH1aDAZ3Ze7LCZ8rBlTIUikYogxD/o1BWX2m1bEb7w7A5OUM0Yr990bDnSvpwXnrMYlA9CJV+AEOq9Nw5r9OblGZLXrMnvbT0RdOUg8LaOLwGKEDj1BjzJVpg5qbJPYm3yb9iCquhZ/pk4hiI4bmTRAZtsxQubt5FNiumiX7NZDHo5jZErAYr3cRSYxvRek1sg0vH9PUqYJcucGxNsZQhVWWQve7q4V1ggAKbhVJrEd5IMOIN9dWek6h6jpXXIqtc+P05H5fbgsm8DFM41bkTev0yIyZldUFJ2uaC5K+h1L0bLYhOlkFXCKEjeUKpC90jzLOCXx1ZvzO5ZrGf1nJyMVwrK/pLir92yrLlVXn/Qd+ST0AEM7qXE+60C2dpwkYy5rM/nGtgTppA1H3bhtS1tQ0F34K2RktvoJ15QVsK5EPRFswjt+o3DT8Q6r0maA7lvxEqOKmDfr7NEqJ1w1F6uYCVjl+VQDNRteHd05gZbZHvwDXTzvDj4STtN6cts27XW8YfSjC1cmn+iHzBSQI50WUjBRGNkJKFOAzOjt5UUt4aQbd5DCiys6w1Po/ayZGLgK8ArrKBhuLdD3iREy7jYTlOY/j3/7qfC4AZ5LdrGoI8DiCVrOL9hkOp0gYPye+VXdSkoUe78fxmao="
  - 'AWS_DEFAULT_REGION=us-east-1'
python:
- '2.7'
install:
- 'pip install yamllint'
- 'pip install awscli'
script:
- 'yamllint . && find . -type f -name ''*.y?ml'' -exec aws cloudformation validate-template --template-body file://{} \;'
