name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:

    - uses: 'actions/checkout@v2'

    - uses: 'actions/setup-python@v2'
      with:
        python-version: '3.8'

    - name: yamlllint
      run: |
        pip install yamllint==1.26.3
        find . -type f \( -name '*.yml' -o -name '*.yaml' \) -a ! -name '.*' | while read file; do set -ex && yamllint "$file"; done;

    - name: cfn-lint
      run: |
        pip install cfn-lint==0.54.1
        cfn-lint -i W2501 W4002 -t **/*.yaml

    - name: license
      run: |
        sudo apt-get install -y shellcheck
        find . -type f -name '*.sh' | while read file; do set -ex && shellcheck -s bash "$file"; done
